[SERVICE]
    Flush        1
    Log_Level    debug
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name   tail
    Path   /containers/overlay-containers/*/userdata/ctr.log
    Parser cri
    Tag    podman.*
    Read_from_Head   On

[FILTER]
    Name   rewrite_tag
    Match  podman.*
    Rule   $message \[HoneyBridge\] keep.$TAG true
    Rule   $stream  stderr             keep.$TAG true

[OUTPUT]
    Name   file
    Match  keep.podman.*
    Path   /var/log
    File   all-containers.log
    Format plain
