[program:http_server80]
command=python3 -u /http/http_server.py 80 "honeypot1"
directory=/http
autorestart=true
priority=20

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0