[program:ssh22]
command=/try-twisted/bin/python3 -u /ssh/ssh.py 22 "honeypot1"
directory=/ssh
autorestart=true
priority=20

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0