[program:telnet23]
command=/try-twisted/bin/python3 -u /telnet/telnet.py 23 "honeypot1"
directory=/telnet
autorestart=true
priority=20

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0