[program:fake_ssh]
command=/try-twisted/bin/python3 -u /app/fake_ssh.py insert_port "insert_name"
autorestart=true
priority=20

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0