[program:insert_ps_name]
command=/bin/sh -c "openssl req -x509 -newkey rsa:4096 -keyout /https/key.pem -out /https/cert.pem -days 365 -nodes -subj '/CN=localhost' && python3 -u /https/https_server.py insert_port 'insert_honeypot_name' 'insert_ip_address'"
directory=/https
autorestart=true
priority=20

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
