[program:insert_ps_name]
command=/try-twisted/bin/python3 -u /ldap/ldap.py --port insert_port --honeypot-name "insert_honeypot_name" --dst-ip "insert_ip_address"
directory=/ldap
autorestart=true
priority=20

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0