[program:insert_ps_name]
command=/try-twisted/bin/python3 -u /services/ssh/ssh.py insert_port "insert_honeypot_name" "insert_ip_address"
directory=/services/ssh
autorestart=true
priority=20

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0