

RUN apt-get install -y --no-install-recommends \
    openssh-server \
    bash \
    ca-certificates \
    sudo \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash -u 1000 -G sudo admin || true \
 && echo "admin:admin" | chpasswd
 
RUN mkdir -p /var/run/sshd && ssh-keygen -A
COPY configs/sshd_config /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
